version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bosta-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-bosta-technical-assessment}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bosta-api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db

volumes:
  postgres_data: